#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "parallel_header.h"

void random_playground(unsigned char* image, int xsize, int ysize)
{
    int idx = 0;
    srand(time(NULL));
    for (int y = 0; y < ysize; y++){
        for (int x = 0; x < xsize; x++){
            // image[idx] = (char)((double)rand()/(double)RAND_MAX+0.5);
            image[idx] = (unsigned char)((int)rand()%2);
            idx++;
        }
    }
}

void write_pgm_image(unsigned char *image, int xsize, int ysize, int maxval, char* filename){

        FILE* image_file; 
        image_file = fopen(filename, "wb"); 
        fprintf(image_file, "P5\n# generated by\n# put here your name\n%d %d %d\n", xsize, ysize, maxval);
    
    
        for (int i=0; i < xsize * ysize; i++){
            fprintf(image_file, "%c", image[i] * 255);
        }

        fclose(image_file);
}

void read_header(int *xsize, int *ysize, int *maxval, char *filename){

    FILE *file = fopen(filename, "rb");
    if(!file){
        perror("Error opening file\n");
    }

    char MagicN[2];

    if(fread(MagicN, 1, 2, file) != 2 || MagicN[0] != 'P' || MagicN[1] != '5'){
        printf("Not a PGM P5 image\n");
        fclose(file);
    }

    // int xsize = -1, ysize = -1, color_maxval = -1;
    char line[50];
    while(fgets(line, sizeof(line), file)){
        if(line[0] == '#'){
            continue;
        }
        else if(sscanf(line, "%d %d\n%d", xsize, ysize, maxval) == 3){
            break;
        } 
    }


    if(*maxval > 255){
        printf("Maxval is too big\n");
        fclose(file);
    }

    else{
        sscanf(line, "%d %d %d\n", xsize, ysize, maxval);
    }
    fclose(file);
}

void read_pgm_image(unsigned char* image, int xsize, int ysize, int maxval, char* filename){
    int elements = 0;

    FILE *file = fopen(filename, "rb");
    if(!file){
        perror("Error opening file\n");
    }

    char MagicN[2];

    if(fread(MagicN, 1, 2, file) != 2 || MagicN[0] != 'P' || MagicN[1] != '5'){
        printf("Not a PGM P5 image\n");
        fclose(file);
    }

    // int xsize = -1, ysize = -1, color_maxval = -1;
    char line[50];
    while(fgets(line, sizeof(line), file)){
        if(line[0] == '#'){
            continue;
        }
        else if(sscanf(line, "%d %d\n%d", &xsize, &ysize, &maxval) == 3){
            break;
        } 
    }


    if(maxval > 255){
        printf("Maxval is too big\n");
        fclose(file);
    }

    else{
        sscanf(line, "%d %d %d\n", &xsize, &ysize, &maxval);
    }
    elements = fread(image, sizeof(unsigned char), xsize * ysize, file);

    for(int idx = 0; idx < xsize * ysize; idx++){
        image[idx] = image[idx]/255;
    }

    fclose(file);
}

unsigned char count_live_neighbors(unsigned char* image, int row, int col, int xsize, int ysize){

  // Periodic boundary

  int xvalues[3];
  int yvalues[3];

  xvalues[1] = col;
  yvalues[1] = row;

  if(row == 0){
    yvalues[0] = ysize - 1;
    yvalues[2] = row + 1;
  }
  else if(row == ysize - 1){
    yvalues[0] = row - 1;
    yvalues[2] = 0;
  }
  else{
   yvalues[0] = row - 1;
   yvalues[2] = row + 1; 
  }

  if(col == 0){
    xvalues[0] = xsize - 1;
    xvalues[2] = col + 1;
  }
  else if(col == xsize - 1){
    xvalues[0] = col - 1;
    xvalues[2] = 0;
  }
  else{
   xvalues[0] = col - 1;
   xvalues[2] = col + 1; 
  }

//   int sum = 0;

    unsigned char sum = 0;
  for(int j = 0; j < 3; j++){
    for(int i = 0; i < 3; i++){
      if (i==1 && j==1){
        continue;
      }
      else{
        // printf("x = %d, y = %d, cell = %c, int value = %d\n", xvalues[i], yvalues[j], image[xvalues[i] + yvalues[j] * xsize] + 48, (int)image[xvalues[i] + yvalues[j] * xsize]);
        sum = sum + image[xvalues[i] + yvalues[j] * xsize];
      }
    }
  }

return sum;
}


void ordered_evolution(unsigned char* image, int xsize, int ysize, int n, int s, char *destination_folder){
  // int dump_idx = 0;

  int snap_idx = -1;
  int maxval = 1;
  if(s == 0){
    snap_idx = n;
  }
  else if(s > 0 && s < n){
    snap_idx = s;
  }
  else{
    printf("Wrong value for \"s\"\n");
  }
  
  for(int step = 0; step < n; step++){
    //ordered evolution
    printf("step = %d ", step);
    for(int y = 0; y < ysize; y++){
      for (int x = 0; x < xsize; x++){
        printf("    y = %d ", y);
        printf("    x = %d\n", x);
        //calculate status of cell in [x][y]
        unsigned char live_neighbors = count_live_neighbors(image, x, y, xsize, ysize);
        if (live_neighbors == 2 || live_neighbors == 3){
          image[x + y * xsize] = 1;
        }
        else if(live_neighbors < 0 || live_neighbors > 8){
          printf("There is an issue with the count of the neighbors that are alive, they cannot be %d\n", (int)live_neighbors);
        }
        else{
          image[x + y * xsize] = 0;
        }
      }
    }
    

    if((step + 1)%snap_idx == 0){
      printf("\nTaking snapshot\n");
      int idx = 0;
        for (int y = 0; y < ysize; y++){
            for (int x = 0; x < xsize; x++){
                printf("%d ", (int)image[idx]);
                idx++;
            }
        printf("\n");
      }
      char title[50];
      snprintf(title, 50, "%s_%d.pbm", destination_folder, step);
      printf("%s\n",title);
      // dump_idx++;
      printf("Writing image\n");
      write_pgm_image(image, xsize, ysize, maxval, title);
      printf("Image written\n");
    }
  }
}

int static_upgrade(unsigned char* image, unsigned char* original_image, int xwidth, int ywidth, int x, int y){
  unsigned char live_neighbors = count_live_neighbors(original_image, x, y, xwidth, ywidth);
  if (live_neighbors == 2 || live_neighbors == 3){
    image[x + y * xwidth] = 1;
  }
  else if(live_neighbors < 0 || live_neighbors > 8){
    printf("There is an issue with the count of the neighbors that are alive, they cannot be %d\n", (int)live_neighbors);
    return 1;
  }
  else{
    image[x + y * xwidth] = 0;
  }

  return 0;
}

void save_snapshot(unsigned char* image, int xwidth, int ywidth, int maxval, char* snap_title, int image_idx){
  int idx = 0;
  printf("Snapshot %d\n", image_idx);
  for(int y = 0; y < ywidth; y++){
    for (int x = 0; x < xwidth; x++){
      printf("%c ", image[idx] + 48);
      idx++;
    }
    printf("\n");
  }
  printf("\n");
  char title[50];
  snprintf(title, 50, "%s_%d.pbm", snap_title, image_idx);
  write_pgm_image(image, xwidth, ywidth, maxval, title);
}